### ISSUE TITLE
Question on py2php

### ISSUE THREAD

**Issue by Brzusto** [dan-da/py2php#3]
Dear dan-da, 

I am very interested in your script. How does this handle imports ?

Is this only translating python code that does not include any library ? 

Congratulations for the tool you built.

**Comment by dan-da** [comment]
> How does this handle imports ?

It converts the "import xxxx.py" to "require_once('xxxx.php')".  In most/many cases that won't work and you'll need to do the right thing manually.

> Is this only translating python code that does not include any library ?


right.  it translates one source code file at a time.

If you have the source to the library, it could possibly be translated also.

For all but the simplest cases, additional porting work will be required for each source file, but py2php handles much of the routine grunt work.
