### ISSUE TITLE
List method

### ISSUE THREAD

**Issue by gareth-ib** [dan-da/py2php#9]
```py
SORT_NONE = lambda rectlist: list(rectlist) # Unsorted
```
converts to..
```php
$SORT_NONE = function ($rectlist) {return list($rectlist);};
```
which is a method in php to split an array into separate variables. like..
```php
list( $var1, $var2 ) = [ 'first', 'second' ];
```
I'm not sure what it's meant to do in python

**Comment by dan-da** [comment]
fixed in 698ec4f56eda5bf5f17ee9a97997bc0434d200eb.    thx.

btw, python doc for list() is [here](https://docs.python.org/2/library/functions.html#func-list)
